In [42]:
import pandas as pd
import numpy as np

df=pd.read_csv('customer_shopping_behavior.csv')
df.sample(5)
# df.info()
# df.describe()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
2483,2484,32,Male,Skirt,Clothing,96,Arizona,S,Teal,Fall,2.9,No,Standard,No,No,8,Debit Card,Monthly
1194,1195,50,Male,Hoodie,Clothing,46,New York,S,Teal,Winter,3.1,No,2-Day Shipping,Yes,Yes,6,Credit Card,Fortnightly
153,154,69,Male,Hoodie,Clothing,55,North Carolina,M,Maroon,Winter,3.2,Yes,Standard,Yes,Yes,22,Debit Card,Annually
3228,3229,37,Female,Jewelry,Accessories,95,Connecticut,M,Yellow,Spring,4.6,No,2-Day Shipping,No,No,27,PayPal,Annually
769,770,52,Male,Socks,Clothing,100,Delaware,M,Silver,Spring,4.3,Yes,Store Pickup,Yes,Yes,8,PayPal,Monthly

In [46]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [47]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [48]:
df.columns=df.columns.str.replace(' ', '_')
df.columns=df.columns.str.lower()
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [51]:
labels=['Young Adults' , 'Adults' , 'Middle-aged' , 'Seniors']

df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)
# df[['Age', 'age_group']].sample(5)

In [52]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [53]:
df[['frequency_of_purchases', 'purchase_frequency_days']].sample(5)

     frequency_of_purchases  purchase_frequency_days
162               Bi-Weekly                       14
1338            Fortnightly                       14
1221              Quarterly                       90
3166            Fortnightly                       14
125          Every 3 Months                       90

In [55]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [60]:
# df=df.drop(columns={'promo_code_used'} , axis=1)
df.head(5)
df.to_csv('customer_shopping_behavior_(updated).csv', index=False)

In [ ]:
# ---------------------------------------------
# PostgreSQL Connection
# Replace the placeholders below with your own
# PostgreSQL credentials before running.
# ---------------------------------------------

from sqlalchemy import create_engine

username = "YOUR_USERNAME"
password = "YOUR_PASSWORD"
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

In [ ]:
# Step 2: Load DataFrame into PostgreSQL

table_name = "customer"      # choose any table name

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behaviour'.

: