In [4]:
import pandas as pd
import numpy as np

df=pd.read_csv('customer_shopping_behaviour.csv')
df.sample(5)
# df.info()
# df.describe()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
498,499,43,Male,Boots,Footwear,78,Iowa,M,Lavender,Spring,3.6,Yes,Free Shipping,Yes,Yes,27,Bank Transfer,Monthly
2059,2060,56,Male,Shorts,Clothing,50,California,XL,Beige,Spring,3.7,No,Express,No,No,50,PayPal,Weekly
3684,3685,29,Female,Skirt,Clothing,86,Pennsylvania,L,Charcoal,Spring,4.4,No,Free Shipping,No,No,47,Credit Card,Bi-Weekly
278,279,57,Male,Sweater,Clothing,95,Hawaii,M,Orange,Spring,3.7,Yes,Express,Yes,Yes,23,Debit Card,Annually
2947,2948,52,Female,Jewelry,Accessories,63,Nebraska,L,Peach,Spring,4.4,No,Standard,No,No,50,Venmo,Annually

In [5]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df.columns=df.columns.str.replace(' ', '_')
df.columns=df.columns.str.lower()
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [8]:
labels=['Young Adults' , 'Adults' , 'Middle-aged' , 'Seniors']

df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)
# df[['Age', 'age_group']].sample(5)

In [9]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [10]:
df[['frequency_of_purchases', 'purchase_frequency_days']].sample(5)

     frequency_of_purchases  purchase_frequency_days
1131                Monthly                       30
1416              Quarterly                       90
2424              Bi-Weekly                       14
1415         Every 3 Months                       90
1740         Every 3 Months                       90

In [11]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [12]:
# df=df.drop(columns={'promo_code_used'} , axis=1)
df.head(5)
df.to_csv('customer_shopping_behavior_(updated).csv', index=False)

In [13]:
# ---------------------------------------------
# PostgreSQL Connection
# Replace the placeholders below with your own
# PostgreSQL credentials before running.
# ---------------------------------------------

from sqlalchemy import create_engine

username = "YOUR_USERNAME"
password = "YOUR_PASSWORD"
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

In [ ]:
# Step 2: Load DataFrame into PostgreSQL

table_name = "customer"      # choose any table name

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")